using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyMotor : MonoBehaviour {
    public float speed = 5.0f;
    public int distance = -15;
    public Vector3 forward = Vector3.forward;

    // Use this for initialization
    void Start () {

    }
	
	// Update is called once per frame
	void Update () {
        //if the enemy generated by the generations script is instantiated at a certain position, this will move it in the correct direction
        EnemySpawn enemySpawnScript = gameObject.GetComponent<EnemySpawn>();
        if (enemySpawnScript.intPos.x <= -10) //make sure the number is the same as spawnX on the Generation script (not including the '-' sign)
        {
            forward = Vector3.forward;
            transform.rotation = Quaternion.Euler(0, 90, 0);
        }

        MoveEnemy();
        if (gameObject.transform.position.x <= distance || gameObject.transform.position.x >= -distance) //if the gameobject goes past a certain point it will destroy it
        {
            Destroy(gameObject);
        }
    }

    private void MoveEnemy()
    {
        //moves enemy forward
        gameObject.transform.Translate(forward * speed * Time.deltaTime);
        //lerps enemy's Y position up and down
        //transform.position = new Vector3(transform.position.x, Mathf.PingPong(Time.time, 1f) + 0.5f, transform.position.z);
    }
}
