using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HighSpeedMotor : MonoBehaviour {

    public float speed = 10.0f;
    public int distance = -15;
    public Vector3 forward = Vector3.forward;

    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //if the highspeed object generated by the generations script is instantiated at a certain position, this will move it in the correct direction
        HighSpeedSpawn highSpeedSpawnScript = gameObject.GetComponent<HighSpeedSpawn>();
        if (highSpeedSpawnScript.intPos.x <= -10)
        {
            forward = Vector3.forward;
            transform.rotation = Quaternion.Euler(0, 90, 0);
        }

        MoveHighSpeed();
        if (gameObject.transform.position.x <= distance || gameObject.transform.position.x >= -distance) //if the gameobject goes past a certain point it will destroy it
        {
            gameObject.SetActive(false); //used to hide the object
            Destroy(gameObject, 16); //[REMEMBER]!!! (if the object has both this script and a spawn script) make sure the number value is always greater than the max delay value on the object's spawn script
        }
    }

    private void MoveHighSpeed()
    {
        //if a highspeed object that instantiated from the generations script is moving in a direction, this will make sure all other highspeed objects behind it move same direction
        gameObject.transform.Translate(forward * speed * Time.deltaTime);
    }
}
