using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LogMotor : MonoBehaviour
{
    public float speed = 2.0f;
    public int distance = -15;
    public Vector3 forward = Vector3.forward;

    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //if the log generated by the generations script is instantiated at a certain position, this will move it in the correct direction
        LogSpawn logSpawnScript = gameObject.GetComponent<LogSpawn>();
        if (logSpawnScript.intPos.x <= -10)
        {
            forward = Vector3.forward;
            transform.rotation = Quaternion.Euler(0, 90, 0);
        }

        //makes logs rush in from the sides and level off to normal speed
        if (gameObject.transform.position.x <= -5 || gameObject.transform.position.x >= 5)
        {
            speed = speed * 1.1f;
        }
        else
            speed = 2; //default speed value

        //makes sure any log objects that are instantiated are instantiated at the right X position based on their rotation
        if (gameObject.transform.rotation == Quaternion.Euler(0, 90, 0))
            logSpawnScript.intPos.x = -10; //make sure the number is the same as spawnX on the Generation script (not including the '-' sign)
        else
            logSpawnScript.intPos.x = 10;  //make sure the number is the same as spawnX on the Generation script

        MoveLog(); //calls MoveLog function
        if (gameObject.transform.position.x <= distance || gameObject.transform.position.x >= -distance) //if the gameobject goes past a certain point it will destroy it
        {
            Destroy(gameObject);
        }
    }

    //moves log
    private void MoveLog()
    {
        //if a log that instantiated from the generations script is moving in a direction, this will make sure all other logs behind it move same direction
        gameObject.transform.Translate(forward * speed * Time.deltaTime);
    }
}